version: '3'

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - ./redis_data:/data
#  app:
#    build: .
#    volumes:
#      - /usr/src/neshkola
#    ports:
#      - "8000:8000"
#    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000